// Complete Spanish translations for every visible string on the public landing
// page. Seeded into the i18n cache (see i18n.tsx) so the EN→ES toggle flips the
// ENTIRE marketing page instantly — no dependency on the /api/translate round-trip
// or any API key. Keys MUST match the exact rendered DOM text, including real
// apostrophes (') and smart quotes (“ ” …). Keep ES values unique per EN key so
// the reverse (ES→EN) swap stays unambiguous.
export const LANDING_ES: Record<string, string> = {
  // Nav
  "How it works": "Cómo funciona",
  "Pricing": "Precios",
  "Guides": "Guías",
  "Waitlist": "Lista de espera",
  "Sign in": "Iniciar sesión",
  "Get started": "Comenzar",

  // Hero
  "For anyone buying or selling cars or parts, new or used": "Para cualquiera que compre o venda autos o piezas, nuevas o usadas",
  "Photograph a car.": "Fotografía un auto.",
  "List every part in seconds.": "Publica cada pieza en segundos.",
  "Ahlam's AI identifies every part, grades its condition, and prices it straight from your photos. Then with a few clicks, it posts straight to eBay, with Facebook and OfferUp coming soon. The hours you spend cataloging and typing listings are gone.": "La IA de Ahlam identifica cada pieza, califica su estado y le pone precio directamente desde tus fotos. Luego, con unos clics, la publica directamente en eBay, y pronto en Facebook y OfferUp. Se acabaron las horas catalogando y escribiendo anuncios.",
  "Start free": "Comienza gratis",
  "See how it works": "Mira cómo funciona",
  "AI powered by Google": "IA con tecnología de Google",
  "Free first month, no card": "Primer mes gratis, sin tarjeta",

  // AI review card (hero visual)
  "AI review card": "Tarjeta de revisión con IA",
  "Part": "Pieza",
  "Alternator": "Alternador",
  "Fits": "Compatible con",
  "Condition": "Estado",
  "Grade B, tested": "Grado B, probado",
  "Suggested": "Sugerido",
  "Post listing": "Publicar anuncio",
  "Grade A": "Grado A",
  "Grade B": "Grado B",
  "Grade C": "Grado C",
  "Grade": "Grado",

  // Beta banner
  "Ahlam is in beta.": "Ahlam está en beta.",
  "Posting to eBay is live now. Facebook, OfferUp, and more are in development. We launch right after the Fourth of July weekend, starting with yards in California and Texas. The first 50 yards to join the waitlist get a full month free with every feature unlocked; later sign-ups get more limited perks.": "La publicación en eBay ya está disponible. Facebook, OfferUp y más están en desarrollo. Lanzamos justo después del fin de semana del 4 de julio, comenzando con yardas en California y Texas. Las primeras 50 yardas que se unan a la lista de espera obtienen un mes completo gratis con todas las funciones desbloqueadas; quienes se registren después tendrán beneficios más limitados.",

  // Countdown
  "Launching in": "Lanzamiento en",
  "Days": "Días",
  "Hours": "Horas",
  "Min": "Min",
  "Sec": "Seg",

  // Partners strip
  "Posts to the places buyers already shop": "Publica en los lugares donde ya compran los compradores",

  // How it works
  "From a photo to posted, in four steps": "De una foto a publicado, en cuatro pasos",
  "Snap photos and let the AI do the cataloging, grading, and pricing. Prefer to type it in? Manual entry is there whenever you want it.": "Toma fotos y deja que la IA haga el catalogado, la calificación y el precio. ¿Prefieres escribirlo? La entrada manual está disponible cuando quieras.",
  "Capture": "Captura",
  "Snap a few photos": "Toma algunas fotos",
  "Use your phone or upload from the lot: the exterior, the parts, the engine bay, the dashboard, and the VIN plate on the windshield. Up to 15 shots per vehicle. More angles mean more parts found and a truer price.": "Usa tu teléfono o sube desde la yarda: el exterior, las piezas, el compartimento del motor, el tablero y la placa del VIN en el parabrisas. Hasta 15 fotos por vehículo. Más ángulos significan más piezas encontradas y un precio más exacto.",
  "Scanning": "Escaneando",
  "Identify": "Identifica",
  "AI catalogs every part": "La IA cataloga cada pieza",
  "The AI reads each photo, names every sellable part, and grades its condition on a consistent A, B, and C rubric. It even reads the VIN and odometer when they show.": "La IA lee cada foto, nombra cada pieza vendible y califica su estado con una escala consistente de A, B y C. Incluso lee el VIN y el odómetro cuando aparecen.",
  "Parts detected": "Piezas detectadas",
  "Hood": "Capó",
  "Left Headlight": "Faro izquierdo",
  "Front Bumper Cover": "Cubierta de defensa delantera",
  "Price": "Precio",
  "Priced from real sales": "Precio basado en ventas reales",
  "We check what the same part actually sells for across eBay, Facebook, and OfferUp, then suggest the median of those real sales. Using the median (not the average) keeps a few stolen or knock-off listings from dragging your price down. Edit any number freely.": "Revisamos a cuánto se vende realmente la misma pieza en eBay, Facebook y OfferUp, y luego sugerimos la mediana de esas ventas reales. Usar la mediana (no el promedio) evita que unos pocos anuncios robados o de imitación bajen tu precio. Edita cualquier número con libertad.",
  "What this part sells for": "A cuánto se vende esta pieza",
  "We suggest the median of real sales, so lowball or knock-off listings can't drag it down.": "Sugerimos la mediana de las ventas reales, para que los anuncios baratos o de imitación no la bajen.",
  "Publish": "Publica",
  "Post everywhere at once": "Publica en todas partes a la vez",
  "Auto-post to eBay and copy clean, ready-to-paste listings for Facebook, OfferUp, and Craigslist, plus your own Ahlam storefront. One scan, every channel.": "Publica automáticamente en eBay y copia anuncios limpios y listos para pegar en Facebook, OfferUp y Craigslist, además de tu propia tienda Ahlam. Un escaneo, todos los canales.",
  "Posted to": "Publicado en",

  // Built for sellers
  "Built for sellers": "Hecho para vendedores",
  "Everything the listing takes, automated": "Todo lo que requiere el anuncio, automatizado",
  "AI grading": "Calificación con IA",
  "A, B, and C condition grades with notes you can edit.": "Calificaciones de estado A, B y C con notas que puedes editar.",
  "Cross-post everywhere": "Publica en todos lados",
  "Auto-post to eBay and one-tap prep for Facebook, OfferUp, and Craigslist.": "Publica automáticamente en eBay y prepara con un toque para Facebook, OfferUp y Craigslist.",
  "Smart pricing": "Precios inteligentes",
  "Each price is the median of what the same part actually sells for across eBay, Facebook, and OfferUp.": "Cada precio es la mediana de lo que realmente se vende la misma pieza en eBay, Facebook y OfferUp.",
  "Private by default": "Privado por defecto",
  "VIN and mileage stay hidden until you choose to share.": "El VIN y el kilometraje permanecen ocultos hasta que decidas compartirlos.",

  // Marketplace
  "A marketplace that works": "Un mercado que funciona",
  "both ways": "en ambos sentidos",
  "Sellers list parts in seconds with the AI. Buyers search every yard's inventory in one place and message the seller direct, with no middleman and no off-platform hand-off.": "Los vendedores publican piezas en segundos con la IA. Los compradores buscan el inventario de cada yarda en un solo lugar y le escriben directo al vendedor, sin intermediarios ni traspasos fuera de la plataforma.",
  "For buyers: find the exact part": "Para compradores: encuentra la pieza exacta",
  "For sellers: reach every buyer": "Para vendedores: llega a cada comprador",
  "Search “2014 Honda Accord front bumper”, a VIN, or a part number…": "Busca “defensa delantera de Honda Accord 2014”, un VIN o un número de pieza…",
  "Browse": "Explorar",
  "views ·": "vistas ·",
  "Message": "Mensaje",
  "Tailgate Assembly": "Conjunto de portón trasero",
  "Headlight Assembly": "Conjunto de faro",
  "Right": "Derecho",
  "Alloy Wheel (Set of 4)": "Rin de aleación (juego de 4)",
  "Engine 2.4L": "Motor 2.4L",
  "Browse the marketplace": "Explorar el mercado",

  // Pricing
  "Simple, transparent pricing": "Precios simples y transparentes",
  "Free for the first 50 yards: a full month, up to 2 cars, every feature unlocked. No card to begin, cancel anytime.": "Gratis para las primeras 50 yardas: un mes completo, hasta 2 autos, todas las funciones desbloqueadas. Sin tarjeta para empezar, cancela cuando quieras.",
  "Free trial": "Prueba gratis",
  "/first month": "/primer mes",
  "The first 50 yards to join get a full month free, with every feature unlocked and no card required. Try the whole platform, not a stripped-down version.": "Las primeras 50 yardas que se unan obtienen un mes completo gratis, con todas las funciones desbloqueadas y sin tarjeta. Prueba toda la plataforma, no una versión recortada.",
  "Free for your first month": "Gratis tu primer mes",
  "Up to 2 cars": "Hasta 2 autos",
  "Every feature we've built, included": "Todas las funciones que hemos creado, incluidas",
  "AI scan & auto-pricing (photo-to-listing)": "Escaneo con IA y precios automáticos (de foto a anuncio)",
  "Access to Ahlam marketplace": "Acceso al mercado de Ahlam",
  "Most popular": "Más popular",
  "Growth": "Crecimiento",
  "/mo": "/mes",
  "For growing dismantlers ready to scale listings and automate their workflow.": "Para desguaces en crecimiento listos para escalar anuncios y automatizar su flujo de trabajo.",
  "10 car listings per month": "10 anuncios de autos por mes",
  "Team access: Owner & Editor": "Acceso de equipo: Propietario y Editor",
  "AI Interchange Assistant": "Asistente de Intercambio con IA",
  "Inventory analytics": "Analíticas de inventario",
  "eBay listing integration": "Integración de anuncios de eBay",
  "Choose Growth": "Elegir Crecimiento",
  "For high-volume yards that need full team access and cross-platform selling power.": "Para yardas de alto volumen que necesitan acceso completo de equipo y poder de venta en varias plataformas.",
  "50 car listings per month": "50 anuncios de autos por mes",
  "Team access: Owner & Unlimited Editors": "Acceso de equipo: Propietario y Editores ilimitados",
  "Full inventory analytics & profit tracking": "Analíticas completas de inventario y seguimiento de ganancias",
  "Cross-platform export (eBay, Facebook, OfferUp, Craigslist)": "Exportación a varias plataformas (eBay, Facebook, OfferUp, Craigslist)",
  "Choose Max": "Elegir Max",
  "Everything in Max, plus we build and host a professional website for your business with your own custom domain, fully managed by Ahlam.": "Todo lo de Max, además construimos y alojamos un sitio web profesional para tu negocio con tu propio dominio personalizado, totalmente administrado por Ahlam.",
  "Unlimited car listings per month": "Anuncios de autos ilimitados por mes",
  "Custom business website, built for you": "Sitio web de negocio personalizado, hecho para ti",
  "Managed domain registration & hosting · priority support": "Registro y alojamiento de dominio administrados · soporte prioritario",
  "Choose Ultimate": "Elegir Ultimate",

  // Dismantler note
  "No email or website? Most dismantlers don't.": "¿Sin correo ni sitio web? La mayoría de los desguaces no los tienen.",
  "On the Ultimate plan we build and host one for you (a professional site, custom domain, and business email) so customers can find you, reach you, and keep coming back.": "Con el plan Ultimate lo construimos y alojamos por ti (un sitio profesional, dominio personalizado y correo de negocio) para que los clientes te encuentren, te contacten y regresen.",

  // How Ahlam works (capability cloud)
  "How Ahlam works": "Cómo funciona Ahlam",
  "Everything it takes to sell, in one place": "Todo lo necesario para vender, en un solo lugar",
  "From scanning and pricing to messaging, orders, and analytics, Ahlam runs the whole operation. Tap any capability to see what it does.": "Desde escanear y poner precio hasta mensajes, pedidos y analíticas, Ahlam maneja toda la operación. Toca cualquier función para ver qué hace.",
  "Tap a capability": "Toca una función",
  "Listing": "Anuncios",
  "Exporting": "Exportación",
  "Messaging": "Mensajería",
  "Orders": "Pedidos",
  "Revenue": "Ingresos",
  "Importing": "Importación",
  "Team": "Equipo",
  "Enterprise": "Empresa",
  "Knows every part": "Conoce cada pieza",
  "Names and grades every sellable part straight from a photo.": "Nombra y califica cada pieza vendible directo desde una foto.",
  "The median of what the same part sells for across platforms. Not a guess, and not dragged down by lowball listings.": "La mediana de lo que se vende la misma pieza en varias plataformas. No es una suposición, ni la bajan los anuncios baratos.",
  "Learns from your sales": "Aprende de tus ventas",
  "Every sale you make sharpens the next price it suggests.": "Cada venta que haces afina el siguiente precio que sugiere.",
  "Connected everywhere": "Conectado en todas partes",
  "One brain behind every marketplace you list on.": "Un solo cerebro detrás de cada mercado en el que publicas.",

  // FAQ
  "Questions": "Preguntas",
  "Answers before you ask": "Respuestas antes de que preguntes",
  "Do I need to know parts to use it?": "¿Necesito saber de piezas para usarlo?",
  "No. That is the point. Photograph the car and the AI names every sellable part, grades its condition, and prices it. You review and post.": "No. Ese es el punto. Fotografía el auto y la IA nombra cada pieza vendible, califica su estado y le pone precio. Tú revisas y publicas.",
  "How accurate is the pricing?": "¿Qué tan precisos son los precios?",
  "We look up what the same part actually sells for across eBay, Facebook, and OfferUp, then suggest the median of those real sales. We use the median, not the average, so a few suspiciously cheap listings (often stolen or knock-off parts) can't drag your price down. Every number is editable, and you can see how confident the AI is on each one.": "Revisamos a cuánto se vende realmente la misma pieza en eBay, Facebook y OfferUp, y luego sugerimos la mediana de esas ventas reales. Usamos la mediana, no el promedio, para que unos pocos anuncios sospechosamente baratos (a menudo piezas robadas o de imitación) no bajen tu precio. Cada número es editable y puedes ver qué tan segura está la IA de cada uno.",
  "Which marketplaces can I post to?": "¿En qué mercados puedo publicar?",
  "Auto-post to eBay, and one-tap copy clean listings for Facebook Marketplace, OfferUp, Craigslist, and Car-Part.com, plus your own Ahlam storefront.": "Publica automáticamente en eBay, y copia con un toque anuncios limpios para Facebook Marketplace, OfferUp, Craigslist y Car-Part.com, además de tu propia tienda Ahlam.",
  "Can I list a part or car manually?": "¿Puedo publicar una pieza o un auto manualmente?",
  "Yes. AI scanning is the fast path, but you can type in a vehicle or a single part by hand any time, with the AI helping write and price it.": "Sí. El escaneo con IA es la vía rápida, pero puedes capturar un vehículo o una sola pieza a mano en cualquier momento, con la IA ayudándote a redactarla y ponerle precio.",
  "Is my VIN and mileage private?": "¿Mi VIN y kilometraje son privados?",
  "Yes. VIN and mileage are read for accuracy but stay hidden on public listings until you choose to share them.": "Sí. El VIN y el kilometraje se leen para mayor exactitud, pero permanecen ocultos en los anuncios públicos hasta que decidas compartirlos.",
  "What does it cost to start?": "¿Cuánto cuesta empezar?",
  "Nothing. Start free with no card. The Pro plan is one flat monthly price with everything included.": "Nada. Empieza gratis sin tarjeta. El plan Pro es un precio mensual fijo con todo incluido.",

  // Contact
  "Get in touch": "Ponte en contacto",
  "See Ahlam on your own inventory": "Ve Ahlam con tu propio inventario",
  "Book a quick walkthrough, reach out with a question, or take a look around. We answer fast.": "Agenda un recorrido rápido, escríbenos con una pregunta o explora. Respondemos rápido.",
  "Book a demo": "Agenda una demo",
  "Contact us": "Contáctanos",
  "Explore the product": "Explora el producto",
  "Have feedback or a feature request?": "¿Tienes comentarios o una sugerencia de función?",
  "Tell us what you think": "Dinos qué opinas",

  // Footer
  "Snap a photo. List every part everywhere: eBay, Facebook, OfferUp, Craigslist, and your own storefront.": "Toma una foto. Publica cada pieza en todas partes: eBay, Facebook, OfferUp, Craigslist y tu propia tienda.",
  "Product": "Producto",
  "The brain": "El cerebro",
  "Resources": "Recursos",
  "FAQ": "Preguntas frecuentes",
  "Company": "Empresa",
  "Feedback": "Comentarios",
  "Ahlam. All rights reserved.": "Ahlam. Todos los derechos reservados.",
};
