// AUTO-GENERATED by scripts/recalibrate-bands.mjs — DO NOT EDIT BY HAND.
//
// Layer 1 recalibrated SOLD-price bands across a basket of popular post-2021
// vehicles — scraped from eBay's public sold listings where reachable, otherwise
// from a Gemini grounded sold-price search.
// Regenerate with: node scripts/recalibrate-bands.mjs
import type { PriceBand } from "./price-bands";

export const GENERATED_BANDS: Record<string, PriceBand> = {
  "fender": {
    "low": 90,
    "high": 350
  },
  "bumper": {
    "low": 190,
    "high": 600
  },
  "headlight": {
    "low": 100,
    "high": 350
  },
  "taillight": {
    "low": 20,
    "high": 300
  },
  "mirror": {
    "low": 40,
    "high": 300
  },
  "wheel": {
    "low": 80,
    "high": 220
  },
  "tire": {
    "low": 50,
    "high": 180
  },
  "glass": {
    "low": 30,
    "high": 100
  },
  "engine": {
    "low": 380,
    "high": 4700
  },
  "transmission": {
    "low": 600,
    "high": 3400
  },
  "alternator": {
    "low": 70,
    "high": 150
  },
  "ac_compressor": {
    "low": 60,
    "high": 170
  }
};

export const GENERATED_AT: string | null = "2026-06-13T17:33:47.965Z";
